#!/usr/bin/env php
<?php
/**
 * Console script
 */
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application(
	'UCT Console',
	implode(' / ', file(__DIR__ . '/.version', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES))
);

// Register commands
$application->add(new Command\AppInit(['en', 'de', 'fr']));

$application->add(new Command\SqlList());
$application->add(new Command\SqlLoad());

$application->add(new Command\UserAdd());
#$application->add(new Command\UserDelete());
#$application->add(new Command\UserList());

$application->add(new Command\AclAdd());
#$application->add(new Command\AclDelete());
#$application->add(new Command\AclList());


$application->run();
