-- Editor configuration -----------------------------------------------------
REPLACE INTO `{{TABLE}}` (`set`, `lang`, `code`, `desc`, `order`) VALUES
('code_set', 'de', 'code_editor_cfg', 'Editor-Einstellungen', -11),
('code_set', 'en', 'code_editor_cfg', 'Editor settings', -11),
('code_set', 'fr', 'code_editor_cfg', 'Paramètres de l\'éditeur', -11);

-- Editor configuration -----------------------------------------------------
REPLACE INTO `{{TABLE}}` (`set`, `lang`, `code`, `desc`, `hint`) VALUES
('code_editor_cfg', 'de', 'Description', 'Universal Code Übersetzer', 'Kopfzeile'),
('code_editor_cfg', 'de', 'Title', 'Universal Code Übersetzer', 'Wird für Browser-Tab und Frontend verwendet'),

('code_editor_cfg', 'en', 'Description', 'Universal Code Translater', 'Header line'),
('code_editor_cfg', 'en', 'Title', 'Universal Code Translater', 'Used for browser tab and frontend'),

('code_editor_cfg', 'fr', 'Description', 'Traducteur de code universel', 'Ligne d\'en-tête'),
('code_editor_cfg', 'fr', 'Title', 'Traducteur de code universel', 'Utilisé pour l\'onglet et le frontal du navigateur');

-- Editor texts -------------------------------------------------------------
REPLACE INTO `{{TABLE}}` (`set`, `lang`, `code`, `desc`) VALUES
('code_admin', '{{NATIVE}}', 'code_editor', '{"multi":1}');

REPLACE INTO `{{TABLE}}` (`set`, `lang`, `code`, `desc`, `order`) VALUES
('code_set', 'en', 'code_editor', 'Editor frontend texts', -10),
('code_set', 'de', 'code_editor', 'Editor Frontend-Texte', -10),
('code_set', 'fr', 'code_editor', 'Éditeur de textes de frontend', -10);

REPLACE INTO `{{TABLE}}` (`set`, `lang`, `code`, `desc`, `quantity`) VALUES
('code_editor', 'en', 'Add', 'Add', 0),
('code_editor', 'en', 'AddCode', 'Add new code', 0),
('code_editor', 'en', 'Administration', 'Administration', 0),
('code_editor', 'en', 'AllCodes', 'All code sets', 0),
('code_editor', 'en', 'AreYouSure', 'Are you sure?', 0),
('code_editor', 'en', 'Code', 'Code', 0),
('code_editor', 'en', 'CodeDeleted', 'Code deleted', 0),
('code_editor', 'en', 'CodeMaxChars', 'max. %d characters', 1),
('code_editor', 'en', 'CodeOrder', 'Code order', 0),
('code_editor', 'en', 'CodeOrderIncrement', 'Order increment', 0),
('code_editor', 'en', 'CodeOrderNotNumeric', 'Code order is not numeric', 0),
('code_editor', 'en', 'CodeRegexFailed', 'Code must match the pattern `[a-zA-Z0-9_]+`', 0),
('code_editor', 'en', 'CodeSaved', 'Code saved', 0),
('code_editor', 'en', 'CodeStateToggled', 'Code state toggled', 0),
('code_editor', 'en', 'CreateSlaveSet', 'Create slave set', 0),
('code_editor', 'en', 'Delete', 'Delete', 0),
('code_editor', 'en', 'Deprecated', 'Deprecated', 0),
('code_editor', 'en', 'DeprecatedHint', 'Code is deprecated, will be displayed as before but not selectable for fututre use', 0),
('code_editor', 'en', 'Description', 'Description', 0),
('code_editor', 'en', 'DisplayLanguage', 'Display', 0),
('code_editor', 'en', 'Edit', 'Edit', 0),
('code_editor', 'en', 'GoogleTranslate', 'Google Translate', 0),
('code_editor', 'en', 'Hint', 'Notes', 0),
('code_editor', 'en', 'InvalidCode', 'Invalid code', 0),
('code_editor', 'en', 'LoggedIn', 'Logged in', 0),
('code_editor', 'en', 'LoggedOut', 'Logged out', 0),
('code_editor', 'en', 'MainTranslationPage', 'Homepage', 0),
('code_editor', 'en', 'MultilineSet', 'Multiline set', 0),
('code_editor', 'en', 'MultilineSetHint', 'Paragraph mode', 0),
('code_editor', 'en', 'NeedsTranslation', '0 | Excellent, no language set need translation work!\n---\n1 | 1 language set (%2$d codes) need translation work\n---\nn | %1$d language sets (%2$d codes) need translation work', 1),
('code_editor', 'en', 'New', 'New', 0),
('code_editor', 'en', 'No', 'No', 0),
('code_editor', 'en', 'none', 'none', 0),
('code_editor', 'en', 'NormalSet', 'Normal set', 0),
('code_editor', 'en', 'NumberOfMany', '#%d of %d', 1),
('code_editor', 'en', 'Other', 'Other', 0),
('code_editor', 'en', 'ParameterSet', 'Parameter set', 0),
('code_editor', 'en', 'ParameterSetHint', 'Parameter sets are not translated', 0),
('code_editor', 'en', 'RecordAdded', 'Record added', 0),
('code_editor', 'en', 'Records', '0 | No records\n---\n1 | 1 record\n---\nn | %d records', 1),
('code_editor', 'en', 'RecordUpdated', 'Record updated', 0),
('code_editor', 'en', 'Save', 'Save', 0),
('code_editor', 'en', 'SelectSetLanguage', 'Select a code set and up to 2 languages', 0),
('code_editor', 'en', 'Skip', 'Skip', 0),
('code_editor', 'en', 'SlaveSet', 'Slave set', 0),
('code_editor', 'en', 'SlaveSetData', 'Set data', 0),
('code_editor', 'en', 'SlaveSetDataHint', 'One entry per line', 0),
('code_editor', 'en', 'SlaveSetHint', 'Slave sets are for translation only', 0),
('code_editor', 'en', 'ToggleState', 'Toggle code state', 0),
('code_editor', 'en', 'TranslationSets', 'Translation sets', 0),
('code_editor', 'en', 'ViewSet', 'View Set', 0),
('code_editor', 'en', 'WithQuantity', 'Quantity-dependent', 0),
('code_editor', 'en', 'WithQuantityHint', 'Contains quantity-dependent content', 0),
('code_editor', 'en', 'Yes', 'Yes', 0),

('code_editor', 'de', 'Add', 'Neu', 0),
('code_editor', 'de', 'AddCode', 'Neuen Code hinzufügen', 0),
('code_editor', 'de', 'Administration', 'Administration', 0),
('code_editor', 'de', 'AllCodes', 'Alle Code Sets', 0),
('code_editor', 'de', 'AreYouSure', 'Sind Sie sicher?', 0),
('code_editor', 'de', 'Code', 'Code', 0),
('code_editor', 'de', 'CodeDeleted', 'Code gelöscht', 0),
('code_editor', 'de', 'CodeMaxChars', 'max. %d Zeichen', 1),
('code_editor', 'de', 'CodeOrder', 'Reihenfolge', 0),
('code_editor', 'de', 'CodeOrderIncrement', 'Schrittweite', 0),
('code_editor', 'de', 'CodeOrderNotNumeric', 'Code-Reihenfolge ist nicht numerisch', 0),
('code_editor', 'de', 'CodeRegexFailed', 'Code muss folgendem Muster entsprechen: `[a-zA-Z0-9_]+`', 0),
('code_editor', 'de', 'CodeSaved', 'Code gesichert', 0),
('code_editor', 'de', 'CodeStateToggled', 'Code Status umgeschaltet', 0),
('code_editor', 'de', 'CreateSlaveSet', 'Slave-Set anlegen', 0),
('code_editor', 'de', 'Delete', 'Löschen', 0),
('code_editor', 'de', 'Deprecated', 'Veraltet', 0),
('code_editor', 'de', 'DeprecatedHint', 'Code ist veraltet, wird angezeigt wie zuvor, ist aber nicht für zukünftige Verwendung auswählbar', 0),
('code_editor', 'de', 'Description', 'Beschreibung', 0),
('code_editor', 'de', 'DisplayLanguage', 'Anzeige', 0),
('code_editor', 'de', 'Edit', 'Bearbeiten', 0),
('code_editor', 'de', 'GoogleTranslate', 'Google Übersetzer', 0),
('code_editor', 'de', 'Hint', 'Hinweis', 0),
('code_editor', 'de', 'InvalidCode', 'Ungültiger Code', 0),
('code_editor', 'de', 'LoggedIn', 'Eingeloggt', 0),
('code_editor', 'de', 'LoggedOut', 'Ausgeloggt', 0),
('code_editor', 'de', 'MainTranslationPage', 'Startseite', 0),
('code_editor', 'de', 'MultilineSet', 'Multiline-Set', 0),
('code_editor', 'de', 'MultilineSetHint', 'Langtext-Modus', 0),
('code_editor', 'de', 'NeedsTranslation', '0 | Hervorragend, kein Sprachensatz braucht Übersetzungsarbeit!\n---\n1 | 1 Sprachensatz (%2$d Einträge) braucht Übersetzungsarbeit\n---\nn | %1$d Sprachensätze (%2$d Einträge) brauchen Übersetzungsarbeit', 1),
('code_editor', 'de', 'New', 'Neu', 0),
('code_editor', 'de', 'No', 'Nein', 0),
('code_editor', 'de', 'none', 'keine', 0),
('code_editor', 'de', 'NormalSet', 'Normales Set', 0),
('code_editor', 'de', 'NumberOfMany', '#%d von %d', 1),
('code_editor', 'de', 'Other', 'Andere', 0),
('code_editor', 'de', 'ParameterSet', 'Parameter-Set', 0),
('code_editor', 'de', 'ParameterSetHint', 'Parameter-Sets werden nicht übersetzt', 0),
('code_editor', 'de', 'RecordAdded', 'Datensatz hinzugefügt', 0),
('code_editor', 'de', 'Records', '0 | Keine Einträge\n---\n1 | 1 Eintrag\n---\nn | %d Einträge', 1),
('code_editor', 'de', 'RecordUpdated', 'Datensatz geändert', 0),
('code_editor', 'de', 'Save', 'Sichern', 0),
('code_editor', 'de', 'SelectSetLanguage', 'Wähle ein Code Set und bis zu 2 Sprachen aus', 0),
('code_editor', 'de', 'Skip', 'Überspringen', 0),
('code_editor', 'de', 'SlaveSet', 'Slave-Set', 0),
('code_editor', 'de', 'SlaveSetData', 'Set Daten', 0),
('code_editor', 'de', 'SlaveSetDataHint', 'Ein Eintrag pro Zeile', 0),
('code_editor', 'de', 'SlaveSetHint', 'Slave-Sets werden nur übersetzt', 0),
('code_editor', 'de', 'ToggleState', 'Status des Codes umschalten', 0),
('code_editor', 'de', 'TranslationSets', 'Übersetzungssets', 0),
('code_editor', 'de', 'ViewSet', 'Set anzeigen', 0),
('code_editor', 'de', 'WithQuantity', 'Mengenabhängig', 0),
('code_editor', 'de', 'WithQuantityHint', 'Enthält mengenabhängigen Text', 0),
('code_editor', 'de', 'Yes', 'Ja', 0),

('code_editor', 'fr', 'Add', 'Ajouter', 0),
('code_editor', 'fr', 'AddCode', 'Ajouter un nouveau code', 0),
('code_editor', 'fr', 'Administration', 'Administration', 0),
('code_editor', 'fr', 'AllCodes', 'Tous les jeux de codes', 0),
('code_editor', 'fr', 'AreYouSure', 'Êtes-vous sûr?', 0),
('code_editor', 'fr', 'Code', 'Code', 0),
('code_editor', 'fr', 'CodeDeleted', 'Code supprimé', 0),
('code_editor', 'fr', 'CodeMaxChars', 'max. %d caractères', 1),
('code_editor', 'fr', 'CodeOrder', 'Commande de code', 0),
('code_editor', 'fr', 'CodeOrderIncrement', 'Incrément', 0),
('code_editor', 'fr', 'CodeOrderNotNumeric', 'L\'ordre du code n\'est pas numérique', 0),
('code_editor', 'fr', 'CodeRegexFailed', 'Le code doit correspondre au modèle `[a-zA-Z0-9_]+`', 0),
('code_editor', 'fr', 'CodeSaved', 'Code enregistré', 0),
('code_editor', 'fr', 'CodeStateToggled', 'État du code basculé', 0),
('code_editor', 'fr', 'CreateSlaveSet', 'Créer un ensemble d\'esclaves', 0),
('code_editor', 'fr', 'Delete', 'Effacer', 0),
('code_editor', 'fr', 'Deprecated', 'Déprécié', 0),
('code_editor', 'fr', 'DeprecatedHint', 'Le code est obsolète, sera affiché comme avant mais ne peut pas être sélectionné pour une utilisation future', 0),
('code_editor', 'fr', 'Description', 'La description', 0),
('code_editor', 'fr', 'DisplayLanguage', 'Afficher', 0),
('code_editor', 'fr', 'Edit', 'Modifier', 0),
('code_editor', 'fr', 'GoogleTranslate', 'Google Traduction', 0),
('code_editor', 'fr', 'Hint', 'Remarques', 0),
('code_editor', 'fr', 'InvalidCode', 'Code invalide', 0),
('code_editor', 'fr', 'LoggedIn', 'Connecté', 0),
('code_editor', 'fr', 'LoggedOut', 'Déconnecté', 0),
('code_editor', 'fr', 'MainTranslationPage', 'Homepage', 0),
('code_editor', 'fr', 'MultilineSet', 'Jeu multiligne', 0),
('code_editor', 'fr', 'MultilineSetHint', 'Mode de paragraphe', 0),
('code_editor', 'fr', 'NeedsTranslation', '0 | Excellent, aucune phrase n\'a besoin d\'être traduite!\n---\n1 | 1 jeu de langues (%2$d entrées) nécessite des travaux de traduction\n---\nn | %1$d jeux de langues (%2$d entrées) nécessitent des travaux de traduction', 1),
('code_editor', 'fr', 'New', 'Nouveau', 0),
('code_editor', 'fr', 'No', 'Non', 0),
('code_editor', 'fr', 'none', 'aucun', 0),
('code_editor', 'fr', 'NormalSet', 'Jeu normal', 0),
('code_editor', 'fr', 'NumberOfMany', '#%d de %d', 1),
('code_editor', 'fr', 'Other', 'Autre', 0),
('code_editor', 'fr', 'ParameterSet', 'Paramètre', 0),
('code_editor', 'fr', 'ParameterSetHint', 'Les jeux de paramètres ne sont pas traduits', 0),
('code_editor', 'fr', 'RecordAdded', 'Enregistrement ajouté', 0),
('code_editor', 'fr', 'Records', '0 | Aucun enregistrement\n---\n1 | 1 enregistrement\n---\nn | %d enregistrements', 1),
('code_editor', 'fr', 'RecordUpdated', 'Données mises à jour', 0),
('code_editor', 'fr', 'Save', 'Enregistrer', 0),
('code_editor', 'fr', 'SelectSetLanguage', 'Sélectionnez un jeu de codes et jusqu\'à 2 langues', 0),
('code_editor', 'fr', 'Skip', 'Sauter', 0),
('code_editor', 'fr', 'SlaveSet', 'Esclave', 0),
('code_editor', 'fr', 'SlaveSetData', 'Définir les données', 0),
('code_editor', 'fr', 'SlaveSetDataHint', 'Une entrée par ligne', 0),
('code_editor', 'fr', 'SlaveSetHint', 'Les ensembles d\'esclaves sont pour la traduction seulement', 0),
('code_editor', 'fr', 'ToggleState', 'Basculer l\'état du code', 0),
('code_editor', 'fr', 'TranslationSets', 'Ensembles de traduction', 0),
('code_editor', 'fr', 'ViewSet', 'Voir l\'ensemble', 0),
('code_editor', 'fr', 'WithQuantity', 'Quantité dépendante', 0),
('code_editor', 'fr', 'WithQuantityHint', 'Contient un contenu dépendant de la quantité', 0),
('code_editor', 'fr', 'Yes', 'Oui', 0);
