#!/usr/bin/env php
<?php
/**
 * Console script
 */
require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;

// Load environment, if exists
if (is_file(__DIR__ . '/../.env')) {
    $dotenv = new Dotenv\Dotenv(__DIR__ . '/..');
    $dotenv->load();
}

// Register commands
$application = new Application();

$application->add(new Command\AppInitCommand());
$application->add(new Command\SqlBootstrapCommand());
$application->add(new Command\SqlListCommand());
$application->add(new Command\SqlLoadCommand());

$application->run();
