DROP TABLE IF EXISTS `{{TABLE}}`;

CREATE TABLE `{{TABLE}}` (
  `set` varchar(16) NOT NULL DEFAULT '' COMMENT 'Code set',
  `lang` varchar(5) NOT NULL DEFAULT '' COMMENT 'Code language',
  `code` varchar(50) NOT NULL DEFAULT '' COMMENT 'Code',
  `desc` text NOT NULL COMMENT 'Translation text',
  `quantity` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Translation contains quantity-dependent text',
  `order` smallint(6) NOT NULL DEFAULT '0' COMMENT 'Sort order',
  `active` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '0: Deprecated / 1: Active',
  PRIMARY KEY (`set`,`lang`,`code`),
  KEY `set_code` (`set`,`code`),
  KEY `code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 PACK_KEYS=1 COMMENT='Universal Code Translation';

INSERT INTO `{{TABLE}}`
(`set`, `lang`, `code`, `desc`, `quantity`, `order`, `active`)
VALUES
('code_admin', 'en', 'code_admin', 'param=1 slave=1', 0, 0, 1),
('code_admin', 'en', 'code_editor', 'multi=1', 0, 0, 1),
('code_editor', 'de', 'Add', 'Neu', 0, 0, 1),
('code_editor', 'de', 'AddCode', 'Neuen Code hinzufügen', 0, 0, 1),
('code_editor', 'de', 'Administration', 'Administration', 0, 0, 1),
('code_editor', 'de', 'AllCodes', 'Alle Code Sets', 0, 0, 1),
('code_editor', 'de', 'AreYouSure', 'Sind Sie sicher?', 0, 0, 1),
('code_editor', 'de', 'Code', 'Code', 0, 0, 1),
('code_editor', 'de', 'CodeDeleted', 'Code gelöscht', 0, 0, 1),
('code_editor', 'de', 'CodeMaxChars', 'max. %d Zeichen', 0, 0, 1),
('code_editor', 'de', 'CodeOrder', 'Reihenfolge', 0, 0, 1),
('code_editor', 'de', 'CodeOrderIncrement', 'Schrittweite', 0, 0, 1),
('code_editor', 'de', 'CodeOrderNotNumeric', 'Code-Reihenfolge ist nicht numerisch', 0, 0, 1),
('code_editor', 'de', 'CodeRegexFailed', 'Code muss folgendem Muster entsprechen: `[a-zA-Z0-9_]+`', 0, 0, 1),
('code_editor', 'de', 'CodeSaved', 'Code gesichert', 0, 0, 1),
('code_editor', 'de', 'CodeStateToggled', 'Code Status umgeschaltet', 0, 0, 0),
('code_editor', 'de', 'CreateSlaveSet', 'Slave-Set anlegen', 0, 0, 1),
('code_editor', 'de', 'Delete', 'Löschen', 0, 0, 1),
('code_editor', 'de', 'Deprecated', 'Veraltet', 0, 0, 1),
('code_editor', 'de', 'DeprecatedHint', 'Code ist veraltet, wird angezeigt wie zuvor, ist aber nicht für zukünftige Verwendung auswählbar', 0, 0, 1),
('code_editor', 'de', 'Description', 'Beschreibung', 0, 0, 1),
('code_editor', 'de', 'DisplayLanguage', 'Anzeige', 0, 0, 1),
('code_editor', 'de', 'Edit', 'Bearbeiten', 0, 0, 1),
('code_editor', 'de', 'GoogleTranslate', 'Google Übersetzer', 0, 0, 1),
('code_editor', 'de', 'InvalidCode', 'Ungültiger Code', 0, 0, 1),
('code_editor', 'de', 'LoggedIn', 'Eingeloggt', 0, 0, 1),
('code_editor', 'de', 'LoggedOut', 'Ausgeloggt', 0, 0, 1),
('code_editor', 'de', 'MainTranslationPage', 'Startseite', 0, 0, 1),
('code_editor', 'de', 'MultilineSet', 'Multiline-Set', 0, 0, 1),
('code_editor', 'de', 'MultilineSetHint', 'Langtext-Modus', 0, 0, 1),
('code_editor', 'de', 'NeedsTranslation', '%d Sprachensätze (%d Einträge) brauchen Übersetzungsarbeit', 0, 0, 1),
('code_editor', 'de', 'New', 'Neu', 0, 0, 1),
('code_editor', 'de', 'No', 'Nein', 0, 0, 1),
('code_editor', 'de', 'none', 'keine', 0, 0, 1),
('code_editor', 'de', 'NormalSet', 'Normales Set', 0, 0, 1),
('code_editor', 'de', 'NumberOfMany', '#%d von %d', 0, 0, 1),
('code_editor', 'de', 'Other', 'Andere', 0, 0, 1),
('code_editor', 'de', 'ParameterSet', 'Parameter-Set', 0, 0, 1),
('code_editor', 'de', 'ParameterSetHint', 'Parameter-Sets werden nicht übersetzt', 0, 0, 1),
('code_editor', 'de', 'RecordAdded', 'Datensatz hinzugefügt', 0, 0, 1),
('code_editor', 'de', 'Records', '0 | Keine Einträge\n---\n1 | 1 Eintrag\n---\nn | %d Einträge', 1, 0, 1),
('code_editor', 'de', 'RecordUpdated', 'Datensatz geändert', 0, 0, 1),
('code_editor', 'de', 'Save', 'Sichern', 0, 0, 1),
('code_editor', 'de', 'SelectSetLanguage', 'Wähle ein Code Set und bis zu 2 Sprachen aus', 0, 0, 1),
('code_editor', 'de', 'Skip', 'Überspringen', 0, 0, 1),
('code_editor', 'de', 'SlaveSet', 'Slave-Set', 0, 0, 1),
('code_editor', 'de', 'SlaveSetData', 'Set Daten', 0, 0, 1),
('code_editor', 'de', 'SlaveSetDataHint', 'Ein Eintrag pro Zeile', 0, 0, 1),
('code_editor', 'de', 'SlaveSetHint', 'Slave-Sets werden nur übersetzt', 0, 0, 1),
('code_editor', 'de', 'ToggleState', 'Status des Codes umschalten', 0, 0, 0),
('code_editor', 'de', 'TranslationSets', 'Übersetzungssets', 0, 0, 1),
('code_editor', 'de', 'ViewSet', 'Set anzeigen', 0, 0, 1),
('code_editor', 'de', 'WithQuantity', 'Mengenabhängig', 0, 0, 0),
('code_editor', 'de', 'WithQuantityHint', 'Enthält mengenabhängigen Text', 0, 0, 0),
('code_editor', 'de', 'Yes', 'Ja', 0, 0, 1),
('code_editor', 'en', 'Add', 'Add', 0, 0, 1),
('code_editor', 'en', 'AddCode', 'Add new code', 0, 0, 1),
('code_editor', 'en', 'Administration', 'Administration', 0, 0, 1),
('code_editor', 'en', 'AllCodes', 'All code sets', 0, 0, 1),
('code_editor', 'en', 'AreYouSure', 'Are you sure?', 0, 0, 1),
('code_editor', 'en', 'Code', 'Code', 0, 0, 1),
('code_editor', 'en', 'CodeDeleted', 'Code deleted', 0, 0, 1),
('code_editor', 'en', 'CodeMaxChars', 'max. %d characters', 0, 0, 1),
('code_editor', 'en', 'CodeOrder', 'Code order', 0, 0, 1),
('code_editor', 'en', 'CodeOrderIncrement', 'Order increment', 0, 0, 1),
('code_editor', 'en', 'CodeOrderNotNumeric', 'Code order is not numeric', 0, 0, 1),
('code_editor', 'en', 'CodeRegexFailed', 'Code must match the pattern `[a-zA-Z0-9_]+`', 0, 0, 1),
('code_editor', 'en', 'CodeSaved', 'Code saved', 0, 0, 1),
('code_editor', 'en', 'CodeStateToggled', 'Code state toggled', 0, 0, 1),
('code_editor', 'en', 'CreateSlaveSet', 'Create slave set', 0, 0, 1),
('code_editor', 'en', 'Delete', 'Delete', 0, 0, 1),
('code_editor', 'en', 'Deprecated', 'Deprecated', 0, 0, 1),
('code_editor', 'en', 'DeprecatedHint', 'Code is deprecated, will be displayed as before but not selectable for fututre use', 0, 0, 1),
('code_editor', 'en', 'Description', 'Description', 0, 0, 1),
('code_editor', 'en', 'DisplayLanguage', 'Display', 0, 0, 1),
('code_editor', 'en', 'Edit', 'Edit', 0, 0, 1),
('code_editor', 'en', 'GoogleTranslate', 'Google Translate', 0, 0, 1),
('code_editor', 'en', 'InvalidCode', 'Invalid code', 0, 0, 1),
('code_editor', 'en', 'LoggedIn', 'Logged in', 0, 0, 1),
('code_editor', 'en', 'LoggedOut', 'Logged out', 0, 0, 1),
('code_editor', 'en', 'MainTranslationPage', 'Homepage', 0, 0, 1),
('code_editor', 'en', 'MultilineSet', 'Multiline set', 0, 0, 1),
('code_editor', 'en', 'MultilineSetHint', 'Paragraph mode', 0, 0, 1),
('code_editor', 'en', 'NeedsTranslation', '%d language sets (%d codes) need translation work', 0, 0, 1),
('code_editor', 'en', 'New', 'New', 0, 0, 1),
('code_editor', 'en', 'No', 'No', 0, 0, 1),
('code_editor', 'en', 'none', 'none', 0, 0, 1),
('code_editor', 'en', 'NormalSet', 'Normal set', 0, 0, 1),
('code_editor', 'en', 'NumberOfMany', '#%d of %d', 0, 0, 1),
('code_editor', 'en', 'Other', 'Other', 0, 0, 1),
('code_editor', 'en', 'ParameterSet', 'Parameter set', 0, 0, 1),
('code_editor', 'en', 'ParameterSetHint', 'Parameter sets are not translated', 0, 0, 1),
('code_editor', 'en', 'RecordAdded', 'Record added', 0, 0, 1),
('code_editor', 'en', 'Records', '0 | No records\n---\n1 | 1 record\n---\nn | %d records', 1, 0, 1),
('code_editor', 'en', 'RecordUpdated', 'Record updated', 0, 0, 1),
('code_editor', 'en', 'Save', 'Save', 0, 0, 1),
('code_editor', 'en', 'SelectSetLanguage', 'Select a code set and up to 2 languages', 0, 0, 1),
('code_editor', 'en', 'Skip', 'Skip', 0, 0, 1),
('code_editor', 'en', 'SlaveSet', 'Slave set', 0, 0, 1),
('code_editor', 'en', 'SlaveSetData', 'Set data', 0, 0, 1),
('code_editor', 'en', 'SlaveSetDataHint', 'One entry per line', 0, 0, 1),
('code_editor', 'en', 'SlaveSetHint', 'Slave sets are for translation only', 0, 0, 1),
('code_editor', 'en', 'ToggleState', 'Toggle code state', 0, 0, 1),
('code_editor', 'en', 'TranslationSets', 'Translation sets', 0, 0, 1),
('code_editor', 'en', 'ViewSet', 'View Set', 0, 0, 1),
('code_editor', 'en', 'WithQuantity', 'Quantity-dependent', 0, 0, 1),
('code_editor', 'en', 'WithQuantityHint', 'Contains quantity-dependent content', 0, 0, 1),
('code_editor', 'en', 'Yes', 'Yes', 0, 0, 1),
('code_editor', 'fr', 'Add', 'Ajouter', 0, 0, 1),
('code_editor', 'fr', 'AddCode', 'Ajouter un nouveau code', 0, 0, 1),
('code_editor', 'fr', 'Administration', 'Administration', 0, 0, 1),
('code_editor', 'fr', 'AllCodes', 'Tous les jeux de codes', 0, 0, 1),
('code_editor', 'fr', 'AreYouSure', 'Êtes-vous sûr?', 0, 0, 1),
('code_editor', 'fr', 'Code', 'Code', 0, 0, 1),
('code_editor', 'fr', 'CodeDeleted', 'Code supprimé', 0, 0, 1),
('code_editor', 'fr', 'CodeMaxChars', 'max. %d caractères', 0, 0, 1),
('code_editor', 'fr', 'CodeOrder', 'Commande de code', 0, 0, 1),
('code_editor', 'fr', 'CodeOrderIncrement', 'Incrément', 0, 0, 1),
('code_editor', 'fr', 'CodeOrderNotNumeric', 'L\'ordre du code n\'est pas numérique', 0, 0, 1),
('code_editor', 'fr', 'CodeRegexFailed', 'Le code doit correspondre au modèle `[a-zA-Z0-9_]+`', 0, 0, 1),
('code_editor', 'fr', 'CodeSaved', 'Code enregistré', 0, 0, 1),
('code_editor', 'fr', 'CodeStateToggled', 'État du code basculé', 0, 0, 0),
('code_editor', 'fr', 'CreateSlaveSet', 'Créer un ensemble d\'esclaves', 0, 0, 1),
('code_editor', 'fr', 'Delete', 'Effacer', 0, 0, 1),
('code_editor', 'fr', 'Deprecated', 'Déprécié', 0, 0, 1),
('code_editor', 'fr', 'DeprecatedHint', 'Le code est obsolète, sera affiché comme avant mais ne peut pas être sélectionné pour une utilisation future', 0, 0, 1),
('code_editor', 'fr', 'Description', 'La description', 0, 0, 1),
('code_editor', 'fr', 'DisplayLanguage', 'Afficher', 0, 0, 1),
('code_editor', 'fr', 'Edit', 'Modifier', 0, 0, 1),
('code_editor', 'fr', 'GoogleTranslate', 'Google Traduction', 0, 0, 1),
('code_editor', 'fr', 'InvalidCode', 'Code invalide', 0, 0, 1),
('code_editor', 'fr', 'LoggedIn', 'Connecté', 0, 0, 1),
('code_editor', 'fr', 'LoggedOut', 'Déconnecté', 0, 0, 1),
('code_editor', 'fr', 'MainTranslationPage', 'Homepage', 0, 0, 1),
('code_editor', 'fr', 'MultilineSet', 'Jeu multiligne', 0, 0, 1),
('code_editor', 'fr', 'MultilineSetHint', 'Mode de paragraphe', 0, 0, 1),
('code_editor', 'fr', 'NeedsTranslation', '%d jeux de langues (%d codes) ont besoin d\'un travail de traduction', 0, 0, 1),
('code_editor', 'fr', 'New', 'Nouveau', 0, 0, 1),
('code_editor', 'fr', 'No', 'Non', 0, 0, 1),
('code_editor', 'fr', 'none', 'aucun', 0, 0, 1),
('code_editor', 'fr', 'NormalSet', 'Jeu normal', 0, 0, 1),
('code_editor', 'fr', 'NumberOfMany', '#%d de %d', 0, 0, 1),
('code_editor', 'fr', 'Other', 'Autre', 0, 0, 1),
('code_editor', 'fr', 'ParameterSet', 'Paramètre', 0, 0, 1),
('code_editor', 'fr', 'ParameterSetHint', 'Les jeux de paramètres ne sont pas traduits', 0, 0, 1),
('code_editor', 'fr', 'RecordAdded', 'Enregistrement ajouté', 0, 0, 1),
('code_editor', 'fr', 'Records', '0 | Aucun enregistrement\n---\n1 | 1 enregistrement\n---\nn | %d enregistrements', 1, 0, 1),
('code_editor', 'fr', 'RecordUpdated', 'Données mises à jour', 0, 0, 1),
('code_editor', 'fr', 'Save', 'Enregistrer', 0, 0, 1),
('code_editor', 'fr', 'SelectSetLanguage', 'Sélectionnez un jeu de codes et jusqu\'à 2 langues', 0, 0, 1),
('code_editor', 'fr', 'Skip', 'Sauter', 0, 0, 1),
('code_editor', 'fr', 'SlaveSet', 'Esclave', 0, 0, 1),
('code_editor', 'fr', 'SlaveSetData', 'Définir les données', 0, 0, 1),
('code_editor', 'fr', 'SlaveSetDataHint', 'Une entrée par ligne', 0, 0, 1),
('code_editor', 'fr', 'SlaveSetHint', 'Les ensembles d\'esclaves sont pour la traduction seulement', 0, 0, 1),
('code_editor', 'fr', 'ToggleState', 'Basculer l\'état du code', 0, 0, 0),
('code_editor', 'fr', 'TranslationSets', 'Ensembles de traduction', 0, 0, 1),
('code_editor', 'fr', 'ViewSet', 'Voir l\'ensemble', 0, 0, 1),
('code_editor', 'fr', 'WithQuantity', 'Quantité dépendante', 0, 0, 0),
('code_editor', 'fr', 'WithQuantityHint', 'Contient un contenu dépendant de la quantité', 0, 0, 0),
('code_editor', 'fr', 'Yes', 'Oui', 0, 0, 1),
('code_lang', 'de', 'de', 'Deutsch', 0, 0, 0),
('code_lang', 'de', 'en', 'Englisch', 0, 0, 0),
('code_lang', 'de', 'fr', 'Französisch', 0, 0, 0),
('code_lang', 'en', 'de', 'German', 0, 1, 1),
('code_lang', 'en', 'en', 'English', 0, 0, 1),
('code_lang', 'en', 'fr', 'French', 0, 1, 1),
('code_lang', 'fr', 'de', 'Allemand', 0, 0, 0),
('code_lang', 'fr', 'en', 'Anglais', 0, 0, 0),
('code_lang', 'fr', 'fr', 'Français', 0, 0, 0),
('code_set', 'de', 'code_editor', 'UCT editor', 0, 0, 1),
('code_set', 'de', 'code_lang', 'Sprache', 0, 0, 0),
('code_set', 'de', 'day', 'Tag', 0, 0, 1),
('code_set', 'de', 'day1', 'Tag (1)', 0, 0, 1),
('code_set', 'de', 'day2', 'Tag (2)', 0, 0, 1),
('code_set', 'de', 'day3', 'Tag (3)', 0, 0, 1),
('code_set', 'de', 'month', 'Monat', 0, 0, 1),
('code_set', 'de', 'month3', 'Monat (3)', 0, 0, 1),
('code_set', 'en', 'code_admin', 'Code admin', 0, -1, 1),
('code_set', 'en', 'code_editor', 'UCT editor', 0, -1, 1),
('code_set', 'en', 'code_lang', 'Language', 0, -2, 1),
('code_set', 'en', 'code_set', 'Code set', 0, -3, 1),
('code_set', 'en', 'day', 'Day', 0, 101, 1),
('code_set', 'en', 'day1', 'Day (1)', 0, 102, 1),
('code_set', 'en', 'day2', 'Day (2)', 0, 103, 1),
('code_set', 'en', 'day3', 'Day (3)', 0, 104, 1),
('code_set', 'en', 'month', 'Month', 0, 111, 1),
('code_set', 'en', 'month3', 'Month (3)', 0, 112, 1),
('code_set', 'fr', 'code_editor', 'UCT éditeur', 0, 0, 1),
('code_set', 'fr', 'code_lang', 'La langue', 0, 0, 0),
('code_set', 'fr', 'day', 'Jour', 0, 0, 0),
('code_set', 'fr', 'day1', 'Jour (1)', 0, 0, 0),
('code_set', 'fr', 'day2', 'Jour (2)', 0, 0, 0),
('code_set', 'fr', 'day3', 'Jour (3)', 0, 0, 0),
('code_set', 'fr', 'month', 'Mois', 0, 0, 0),
('code_set', 'fr', 'month3', 'Mois (3)', 0, 0, 0),
('day', 'de', '0', 'Sonntag', 0, 0, 1),
('day', 'de', '1', 'Montag', 0, 0, 1),
('day', 'de', '2', 'Dienstag', 0, 0, 1),
('day', 'de', '3', 'Mittwoch', 0, 0, 1),
('day', 'de', '4', 'Donnerstag', 0, 0, 1),
('day', 'de', '5', 'Freitag', 0, 0, 1),
('day', 'de', '6', 'Samstag', 0, 0, 1),
('day', 'en', '0', 'Sunday', 0, 0, 1),
('day', 'en', '1', 'Monday', 0, 1, 1),
('day', 'en', '2', 'Tuesday', 0, 2, 1),
('day', 'en', '3', 'Wednesday', 0, 3, 1),
('day', 'en', '4', 'Thursday', 0, 4, 1),
('day', 'en', '5', 'Friday', 0, 5, 1),
('day', 'en', '6', 'Saturday', 0, 6, 1),
('day', 'fr', '0', 'Dimanche', 0, 0, 0),
('day', 'fr', '1', 'Lundi', 0, 0, 0),
('day', 'fr', '2', 'Mardi', 0, 0, 0),
('day', 'fr', '3', 'Mercredi', 0, 0, 0),
('day', 'fr', '4', 'Jeudi', 0, 0, 0),
('day', 'fr', '5', 'Vendredi', 0, 0, 0),
('day', 'fr', '6', 'Samedi', 0, 0, 0),
('day1', 'de', '0', 'S', 0, 0, 1),
('day1', 'de', '1', 'M', 0, 0, 1),
('day1', 'de', '2', 'D', 0, 0, 1),
('day1', 'de', '3', 'M', 0, 0, 1),
('day1', 'de', '4', 'D', 0, 0, 1),
('day1', 'de', '5', 'F', 0, 0, 1),
('day1', 'de', '6', 'S', 0, 0, 1),
('day1', 'en', '0', 'S', 0, 0, 1),
('day1', 'en', '1', 'M', 0, 1, 1),
('day1', 'en', '2', 'T', 0, 2, 1),
('day1', 'en', '3', 'W', 0, 3, 1),
('day1', 'en', '4', 'T', 0, 4, 1),
('day1', 'en', '5', 'F', 0, 5, 1),
('day1', 'en', '6', 'S', 0, 6, 1),
('day1', 'fr', '0', 'D', 0, 0, 0),
('day1', 'fr', '1', 'L', 0, 0, 0),
('day1', 'fr', '2', 'M', 0, 0, 0),
('day1', 'fr', '3', 'M', 0, 0, 0),
('day1', 'fr', '4', 'J', 0, 0, 0),
('day1', 'fr', '5', 'V', 0, 0, 0),
('day1', 'fr', '6', 'S', 0, 0, 0),
('day2', 'de', '0', 'So', 0, 0, 1),
('day2', 'de', '1', 'Mo', 0, 0, 1),
('day2', 'de', '2', 'Di', 0, 0, 1),
('day2', 'de', '3', 'Mi', 0, 0, 1),
('day2', 'de', '4', 'Do', 0, 0, 1),
('day2', 'de', '5', 'Fr', 0, 0, 1),
('day2', 'de', '6', 'Sa', 0, 0, 1),
('day2', 'en', '0', 'Su', 0, 0, 1),
('day2', 'en', '1', 'Mo', 0, 1, 1),
('day2', 'en', '2', 'Tu', 0, 2, 1),
('day2', 'en', '3', 'We', 0, 3, 1),
('day2', 'en', '4', 'Th', 0, 4, 1),
('day2', 'en', '5', 'Fr', 0, 5, 1),
('day2', 'en', '6', 'Sa', 0, 6, 1),
('day2', 'fr', '0', 'Di', 0, 0, 0),
('day2', 'fr', '1', 'Lu', 0, 0, 0),
('day2', 'fr', '2', 'Ma', 0, 0, 0),
('day2', 'fr', '3', 'Me', 0, 0, 0),
('day2', 'fr', '4', 'Je', 0, 0, 0),
('day2', 'fr', '5', 'Ve', 0, 0, 0),
('day2', 'fr', '6', 'Sa', 0, 0, 0),
('day3', 'de', '0', 'Son', 0, 0, 1),
('day3', 'de', '1', 'Mon', 0, 0, 1),
('day3', 'de', '2', 'Die', 0, 0, 1),
('day3', 'de', '3', 'Mit', 0, 0, 1),
('day3', 'de', '4', 'Don', 0, 0, 1),
('day3', 'de', '5', 'Fre', 0, 0, 1),
('day3', 'de', '6', 'Sam', 0, 0, 1),
('day3', 'en', '0', 'Sun', 0, 0, 1),
('day3', 'en', '1', 'Mon', 0, 1, 1),
('day3', 'en', '2', 'Tue', 0, 2, 1),
('day3', 'en', '3', 'Wed', 0, 3, 1),
('day3', 'en', '4', 'Thu', 0, 4, 1),
('day3', 'en', '5', 'Fri', 0, 5, 1),
('day3', 'en', '6', 'Sat', 0, 6, 1),
('day3', 'fr', '0', 'Dim', 0, 0, 0),
('day3', 'fr', '1', 'Lun', 0, 0, 0),
('day3', 'fr', '2', 'Mar', 0, 0, 0),
('day3', 'fr', '3', 'Mer', 0, 0, 0),
('day3', 'fr', '4', 'Jeu', 0, 0, 0),
('day3', 'fr', '5', 'Ven', 0, 0, 0),
('day3', 'fr', '6', 'Sam', 0, 0, 0),
('month', 'de', '1', 'Januar', 0, 0, 1),
('month', 'de', '10', 'Oktober', 0, 0, 1),
('month', 'de', '11', 'November', 0, 0, 1),
('month', 'de', '12', 'Dezember', 0, 0, 1),
('month', 'de', '2', 'Februar', 0, 0, 1),
('month', 'de', '3', 'März', 0, 0, 1),
('month', 'de', '4', 'April', 0, 0, 1),
('month', 'de', '5', 'Mai', 0, 0, 1),
('month', 'de', '6', 'Juni', 0, 0, 1),
('month', 'de', '7', 'Juli', 0, 0, 1),
('month', 'de', '8', 'August', 0, 0, 1),
('month', 'de', '9', 'September', 0, 0, 1),
('month', 'en', '1', 'January', 0, 1, 1),
('month', 'en', '10', 'October', 0, 10, 1),
('month', 'en', '11', 'November', 0, 11, 1),
('month', 'en', '12', 'December', 0, 12, 1),
('month', 'en', '2', 'February', 0, 2, 1),
('month', 'en', '3', 'March', 0, 3, 1),
('month', 'en', '4', 'April', 0, 4, 1),
('month', 'en', '5', 'May', 0, 5, 1),
('month', 'en', '6', 'June', 0, 6, 1),
('month', 'en', '7', 'July', 0, 7, 1),
('month', 'en', '8', 'August', 0, 8, 1),
('month', 'en', '9', 'September', 0, 9, 1),
('month', 'fr', '1', 'Janvier', 0, 0, 0),
('month', 'fr', '10', 'Octobre', 0, 0, 0),
('month', 'fr', '11', 'Novembre', 0, 0, 0),
('month', 'fr', '12', 'Décembre', 0, 0, 0),
('month', 'fr', '2', 'Février', 0, 0, 0),
('month', 'fr', '3', 'Mars', 0, 0, 0),
('month', 'fr', '4', 'Avril', 0, 0, 0),
('month', 'fr', '5', 'Mai', 0, 0, 0),
('month', 'fr', '6', 'Juin', 0, 0, 0),
('month', 'fr', '7', 'Juillet', 0, 0, 0),
('month', 'fr', '8', 'Août', 0, 0, 0),
('month', 'fr', '9', 'Septembre', 0, 0, 0),
('month3', 'de', '1', 'Jan', 0, 0, 1),
('month3', 'de', '10', 'Okt', 0, 0, 1),
('month3', 'de', '11', 'Nov', 0, 0, 1),
('month3', 'de', '12', 'Dez', 0, 0, 1),
('month3', 'de', '2', 'Feb', 0, 0, 1),
('month3', 'de', '3', 'Mär', 0, 0, 1),
('month3', 'de', '4', 'Apr', 0, 0, 1),
('month3', 'de', '5', 'Mai', 0, 0, 1),
('month3', 'de', '6', 'Jun', 0, 0, 1),
('month3', 'de', '7', 'Jul', 0, 0, 1),
('month3', 'de', '8', 'Aug', 0, 0, 1),
('month3', 'de', '9', 'Sep', 0, 0, 1),
('month3', 'en', '1', 'Jan', 0, 1, 1),
('month3', 'en', '10', 'Oct', 0, 10, 1),
('month3', 'en', '11', 'Nov', 0, 11, 1),
('month3', 'en', '12', 'Dec', 0, 12, 1),
('month3', 'en', '2', 'Feb', 0, 2, 1),
('month3', 'en', '3', 'Mar', 0, 3, 1),
('month3', 'en', '4', 'Apr', 0, 4, 1),
('month3', 'en', '5', 'May', 0, 5, 1),
('month3', 'en', '6', 'Jun', 0, 6, 1),
('month3', 'en', '7', 'Jul', 0, 7, 1),
('month3', 'en', '8', 'Aug', 0, 8, 1),
('month3', 'en', '9', 'Sep', 0, 9, 1),
('month3', 'fr', '1', 'Jan', 0, 0, 0),
('month3', 'fr', '10', 'Oct', 0, 0, 0),
('month3', 'fr', '11', 'Nov', 0, 0, 0),
('month3', 'fr', '12', 'Dec', 0, 0, 0),
('month3', 'fr', '2', 'Fev', 0, 0, 0),
('month3', 'fr', '3', 'Mar', 0, 0, 0),
('month3', 'fr', '4', 'Avr', 0, 0, 0),
('month3', 'fr', '5', 'Mai', 0, 0, 0),
('month3', 'fr', '6', 'Jui', 0, 0, 0),
('month3', 'fr', '7', 'Jul', 0, 0, 0),
('month3', 'fr', '8', 'Aou', 0, 0, 0),
('month3', 'fr', '9', 'Sep', 0, 0, 0);
